name: Backup Tags

on:
  push:
    tags:
      - '*'

jobs:
  backup-tags:
    name: Backup Tags
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get tag-sha dict
        id: tag-sha-dict
        run: |
          dict=$(python3 ./.github/workflows/tag-sha-config 2>&1)
          echo $dict[$@]
      - name: commit json
        run: |
          # git config --global user.email "${GITHUB_ACTOR}"
          # git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git add tag-sha-config.json
          git commit -m "update tags sha"
          git push origin HEAD:release