name: Backup Tags

on:
  push:
    tags:
      - '*'

jobs:
  backup-tags:
    name: Backup Tags
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install pygithub
        run: pip3 install pygithub
      - name: get tag-sha dict
        id: tag-sha-dict
        run: |
          dict=$(python3 ./.github/workflows/a 2>&1)
          echo $dict[$@]
          curl \
          -X PUT \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/secrets/TAG_SHA \
          -d '{"encrypted_value":$dict}'