name: Recover Tags
on:
  delete

jobs:
  recover-tags:
    name: Recover Tags
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: echo
        run: echo ${GITHUB_REF}