name: Recover Tags
on:
  delete

jobs:
  recover-tags:
    name: Recover Tags
    runs-on: ubuntu-20.04
    steps:
      - name: echo
        run: |
          echo ${{ github.event.ref }}
          echo ${{ github.ref }}