name: Run Litani Tests
on: push

jobs:
  test-litani:
    if: ${{ github.event.label.name == 'test' }}
    name: Run Litani Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install awscli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run aws cli commands
        run: aws ec2 describe-instances