name: Run Litani Tests
on:
  workflow_dispatch:
    branches: [ release, develop ]
  push:
    branches: [ release, develop ]
  pull_request:
    branches: [ release, develop ]
    types: [ labeled ]

jobs:
  test-litani:
    if: "!contains(github.event.pull_request.labels.*.name, 'no-test')" or "contains(github.event.pull_request.labels.*.name, 'test')
    name: Run Litani Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew install ninja
          python3 -m pip install jinja2
      - name: Run Unit and e2e tests
        run: ./test/run

