name: My workflow
on:
  workflow_dispatch:
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout proof-ci action
        uses: actions/checkout@v2
        with:
          repository: model-checking/proof-ci
          ref: refs/heads/post-parameters-to-ssm-and-deploy-conditionally
          # GitHub's personal access token with access to `my-organization/awesome-action`
          token: ${{ secrets.BOT_USER_PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false
          path: ./.github/actions/proof-ci
      - run: ls .github
      - run: ls .github/actions
      - run: ls .github/actions/proof-ci

