name: My workflow
on:
  workflow_dispatch:
jobs:
  do-something:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout proof-ci action
        uses: actions/checkout@v2
        with:
          repository: model-checking/proof-ci
          ref: refs/heads/post-parameters-to-ssm-and-deploy-conditionally
          # GitHub's personal access token with access to `my-organization/awesome-action`
          token: ${{ secrets.BOT_USER_PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false
          path: ./.github/actions/proof-ci
      - uses: ./.github/actions/proof-ci
        with:
          # required
          cbmc-version: 5.59.0
          cbmc-viewer-version: 2.10
          github-repo-owner: ronakfof
          github-repo-name: s2n-tls
          github-repo-visibility: ${{ fromJson(toJson(github.event.repository)).visibility }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          iam-role: ${{ secrets.IAM_ROLE }}
          litani-version: 1.26.0
          bot-user-personal-access-token: ${{ secrets.BOT_USER_PERSONAL_ACCESS_TOKEN }}
          proof-container-image: ${{ steps.proof-container-image.outputs.result }}
          proofs-command: ./run-cbmc-proofs.py
          proofs-dir: tests/cbmc/proofs
          region: ${{ secrets.REGION }}
          # not required
          codebuild-compute-type: BUILD_GENERAL1_2XLARGE
          codebuild-environment-type: LINUX_CONTAINER
          external-sat-solver: kissat
          suffix-custom-version-id: test
